export const navigationItems = [
  { href: '/', label: 'Overview', group: 'main' },
  { href: '/pcap', label: '1. Upload PCAP', group: 'flow' },
  { href: '/alerts', label: '2. Raw Alerts', group: 'flow' },
  { href: '/normalized-alerts', label: '3. Normalization', group: 'flow' },
  { href: '/recommendations', label: '4. Playbook Recommendation', group: 'flow' },
  { href: '/explanations', label: '5. Recommendation Explanation', group: 'flow' },
  { href: '/analyst-review', label: '6. Analyst Review', group: 'flow' },
  { href: '/approvals', label: '7. Analyst Approval', group: 'flow' },
  { href: '/workflows', label: '8. Workflow Execution', group: 'flow' },
  { href: '/incidents', label: '9. Incident Tracking', group: 'flow' },
  { href: '/reports', label: '10. Report', group: 'flow' },
  { href: '/evaluation', label: '11. Evaluation', group: 'flow' },
  { href: '/playbooks', label: 'Playbook Library', group: 'library' },
  { href: '/demo', label: 'SOAR Run Console', group: 'library' },
];
