export const navigationItems = [
  { href: '/', label: 'Tổng quan' },
  { href: '/alerts', label: 'Cảnh báo (Alert)' },
  { href: '/normalized-alerts', label: 'Cảnh báo chuẩn hóa' },
  { href: '/playbooks', label: 'Playbook' },
  { href: '/recommendations', label: 'Khuyến nghị' },
  { href: '/explanations', label: 'Giải thích' },
  { href: '/approvals', label: 'Phê duyệt' },
  { href: '/incidents', label: 'Sự cố (Incident)' },
  { href: '/workflows', label: 'Workflow' },
  { href: '/reports', label: 'Báo cáo (Report)' },
  { href: '/evaluation', label: 'Đánh giá' },
  { href: '/demo', label: 'Chạy demo SOAR' },
  { href: '/pcap-demo', label: 'PCAP demo' },
];
