import {
  AlertSource,
  AlertType,
  RAW_ALERT_MOCK_SCENARIOS,
  Severity,
} from '@soc-soar/shared';

import type { CreateRawAlertDto } from './dto/create-raw-alert.dto';

export type RawAlertMockScenario = (typeof RAW_ALERT_MOCK_SCENARIOS)[number];

export const RAW_ALERT_MOCK_PAYLOADS: Record<RawAlertMockScenario, CreateRawAlertDto> = {
  'port-scan': {
    source: AlertSource.MOCK,
    sourceAlertId: 'SRC-PORT-SCAN-001',
    title: 'Possible port scan detected from external source',
    description: 'Multiple destination ports were probed on a lab server.',
    alertType: AlertType.PORT_SCAN,
    severity: Severity.MEDIUM,
    confidence: 82,
    observedAt: '2026-05-03T07:00:00.000Z',
    sourceIp: '203.0.113.24',
    targetIp: '10.10.20.15',
    protocol: 'tcp',
    targetPort: 22,
    hostname: 'soc-lab-jump-01',
    assetId: 'AST-JUMP-01',
    rawPayload: {
      detector: 'mock-scanner',
      ports: [22, 80, 443, 3389],
      totalAttempts: 47,
    },
    tags: ['demo', 'reconnaissance'],
  },
  'icmp-flood': {
    source: AlertSource.MOCK,
    sourceAlertId: 'SRC-ICMP-FLOOD-001',
    title: 'ICMP ping flood against public web edge',
    description: 'A burst of ICMP echo requests suggests volumetric activity.',
    alertType: AlertType.ICMP_FLOOD,
    severity: Severity.HIGH,
    confidence: 88,
    observedAt: '2026-05-03T07:05:00.000Z',
    sourceIp: '198.51.100.9',
    targetIp: '10.10.10.5',
    protocol: 'icmp',
    hostname: 'soc-edge-web-01',
    assetId: 'AST-WEB-EDGE-01',
    rawPayload: {
      detector: 'mock-flood-sensor',
      packetsPerSecond: 24000,
      packetType: 'echo-request',
    },
    tags: ['demo', 'dos'],
  },
  'sql-injection': {
    source: AlertSource.MOCK,
    sourceAlertId: 'SRC-SQLI-001',
    title: 'Suspicious SQLi pattern in login endpoint',
    description: 'Request includes union select keywords in a web parameter.',
    alertType: AlertType.WEB_SQL_INJECTION,
    severity: Severity.HIGH,
    confidence: 91,
    observedAt: '2026-05-03T07:10:00.000Z',
    sourceIp: '203.0.113.77',
    targetIp: '10.10.30.25',
    protocol: 'http',
    targetPort: 443,
    httpUri: '/login?user=admin%27%20union%20select%201,2--',
    hostname: 'soc-lab-app-01',
    assetId: 'AST-APP-01',
    rawPayload: {
      detector: 'mock-waf',
      httpMethod: 'GET',
      matchedRule: 'union-select',
    },
    tags: ['demo', 'web-attack'],
  },
  xss: {
    source: AlertSource.MOCK,
    sourceAlertId: 'SRC-XSS-001',
    title: 'Potential XSS payload observed in comment form',
    description: 'User-supplied content contains script tags and event handlers.',
    alertType: AlertType.WEB_XSS,
    severity: Severity.MEDIUM,
    confidence: 79,
    observedAt: '2026-05-03T07:15:00.000Z',
    sourceIp: '192.0.2.44',
    targetIp: '10.10.30.25',
    protocol: 'http',
    targetPort: 443,
    httpUri: '/comments',
    username: 'guest-user',
    hostname: 'soc-lab-app-01',
    assetId: 'AST-APP-01',
    rawPayload: {
      detector: 'mock-waf',
      payloadSnippet: '<script>alert(1)</script>',
      matchedRule: 'script-tag',
    },
    tags: ['demo', 'web-attack'],
  },
  'suspicious-dns': {
    source: AlertSource.MOCK,
    sourceAlertId: 'SRC-DNS-001',
    title: 'Suspicious domain resolution from workstation',
    description: 'Host repeatedly queried an uncommon domain with entropy-heavy subdomains.',
    alertType: AlertType.SUSPICIOUS_DNS_QUERY,
    severity: Severity.MEDIUM,
    confidence: 76,
    observedAt: '2026-05-03T07:20:00.000Z',
    sourceIp: '10.10.40.81',
    protocol: 'dns',
    dnsQuery: 's9d2ja0.example-malicious.test',
    hostname: 'soc-lab-endpoint-07',
    assetId: 'AST-ENDPOINT-07',
    rawPayload: {
      detector: 'mock-dns-monitor',
      queryType: 'A',
      responseCode: 'NOERROR',
    },
    tags: ['demo', 'dns'],
  },
  'botnet-c2': {
    source: AlertSource.MOCK,
    sourceAlertId: 'SRC-BOTNET-C2-001',
    title: 'Possible botnet C2 beacon from endpoint',
    description: 'Endpoint shows repeated outbound connections to a suspected command-and-control host.',
    alertType: AlertType.BOTNET_C2,
    severity: Severity.HIGH,
    confidence: 86,
    observedAt: '2026-05-03T07:25:00.000Z',
    sourceIp: '10.10.40.92',
    targetIp: '198.51.100.200',
    protocol: 'http',
    targetPort: 8080,
    httpUri: '/gate/checkin',
    dnsQuery: 'c2-demo.example-malicious.test',
    hostname: 'soc-lab-endpoint-12',
    assetId: 'AST-ENDPOINT-12',
    rawPayload: {
      detector: 'mock-network-monitor',
      beaconIntervalSeconds: 60,
      repeatedConnections: 42,
    },
    tags: ['demo', 'malware', 'c2'],
  },
};
