import {
  AlertType,
  ApprovalPolicy,
  AutomationLevel,
  IncidentCategory,
  PlaybookActionType,
  PlaybookStatus,
  PlaybookStepRisk,
  Severity,
  type Playbook as SharedPlaybook,
  type PlaybookAction,
  type PlaybookCondition,
  type PlaybookReference,
} from '@soc-soar/shared';

type SeedPlaybook = Omit<SharedPlaybook, 'createdAt' | 'updatedAt'>;

function buildAction(input: PlaybookAction): PlaybookAction {
  return input;
}

function buildCondition(input: PlaybookCondition): PlaybookCondition {
  return input;
}

function buildReference(input: PlaybookReference): PlaybookReference {
  return input;
}

const NIST_REFERENCE = buildReference({
  name: 'NIST Incident Response Lifecycle',
  type: 'standard',
  note: 'Used as high-level incident handling structure for triage, analysis, containment preparation, and documentation.',
});

const THESIS_REFERENCE = buildReference({
  name: 'SOARisk Phase 5 Dataset Design',
  type: 'internal_design',
  note: 'Prototype playbook dataset is intentionally concise, mock-only, and thesis-oriented.',
});

const MOCK_OPERATIONS_REFERENCE = buildReference({
  name: 'Mock Action Guardrail',
  type: 'guideline',
  note: 'Sensitive actions are modeled as requests or recommendations only and never execute directly.',
});

export const PLAYBOOK_SEED_DATA: SeedPlaybook[] = [
  {
    playbookId: 'PB-001',
    name: 'Generic Alert Triage',
    description: 'Baseline triage template for alerts that do not map cleanly to a more specific incident category.',
    incidentCategory: IncidentCategory.GENERIC,
    supportedAlertTypes: [AlertType.GENERIC],
    requiredFields: ['title', 'severity'],
    optionalFields: ['sourceIp', 'targetIp', 'hostname', 'username'],
    severityRange: [Severity.LOW, Severity.MEDIUM, Severity.HIGH, Severity.CRITICAL],
    assetContext: ['generic_asset', 'hostname', 'ipAddress'],
    conditions: [
      buildCondition({
        field: 'alertType',
        operator: 'equals',
        value: AlertType.GENERIC,
        weightHint: 100,
        description: 'Matches normalized alerts that remain generic after deterministic normalization.',
      }),
      buildCondition({
        field: 'severity',
        operator: 'exists',
        description: 'Requires at least a baseline severity to support triage.',
      }),
    ],
    actions: [
      buildAction({
        step: 1,
        action: 'create_incident',
        type: PlaybookActionType.CASE_MANAGEMENT,
        description: 'Create a mock incident record to anchor analyst triage and evidence review.',
        requiredFields: ['title', 'severity'],
        produces: ['incidentRecord'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 2,
        action: 'enrich_basic_observables',
        type: PlaybookActionType.ENRICHMENT,
        description: 'Collect available source, target, host, and account context from the alert record.',
        requiredFields: ['title'],
        produces: ['observableSummary'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 3,
        action: 'check_asset_context',
        type: PlaybookActionType.ASSET_CONTEXT,
        description: 'Review whether the affected asset has known business criticality or ownership context.',
        requiredFields: ['title'],
        produces: ['assetContextReview'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 4,
        action: 'investigate_available_evidence',
        type: PlaybookActionType.INVESTIGATION,
        description: 'Review normalization notes and evidence to determine whether the alert can be categorized further.',
        requiredFields: ['title'],
        produces: ['triageNotes'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 5,
        action: 'mock_notify_analyst',
        type: PlaybookActionType.NOTIFICATION,
        description: 'Send a mock analyst notification summarizing the alert and remaining unknowns.',
        requiredFields: ['title'],
        produces: ['analystNotificationDraft'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 6,
        action: 'generate_response_summary',
        type: PlaybookActionType.REPORTING,
        description: 'Generate a concise triage summary for future recommendation and incident phases.',
        requiredFields: ['title'],
        produces: ['responseSummary'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: false,
      }),
    ],
    approvalRequired: false,
    approvalPolicy: ApprovalPolicy.NONE,
    automationLevel: AutomationLevel.MANUAL,
    status: PlaybookStatus.ACTIVE,
    references: [NIST_REFERENCE, THESIS_REFERENCE],
    version: '1.0.0',
    tags: ['seed', 'triage', 'generic'],
  },
  {
    playbookId: 'PB-002',
    name: 'Port Scan Investigation',
    description: 'Structured reconnaissance triage for likely port scanning from a single source toward one or more internal targets.',
    incidentCategory: IncidentCategory.RECONNAISSANCE,
    supportedAlertTypes: [AlertType.PORT_SCAN],
    requiredFields: ['sourceIp', 'targetIp', 'protocol'],
    optionalFields: ['sourcePort', 'targetPort', 'hostname', 'assetId'],
    severityRange: [Severity.LOW, Severity.MEDIUM, Severity.HIGH],
    assetContext: ['network_edge', 'server', 'firewallZone'],
    conditions: [
      buildCondition({
        field: 'alertType',
        operator: 'equals',
        value: AlertType.PORT_SCAN,
        weightHint: 100,
        description: 'Primary match for normalized port scan alerts.',
      }),
      buildCondition({
        field: 'sourceIp',
        operator: 'exists',
        description: 'Requires a source IP to analyze scanning behavior.',
      }),
      buildCondition({
        field: 'targetIp',
        operator: 'exists',
        description: 'Requires at least one destination host for scope review.',
      }),
    ],
    actions: [
      buildAction({
        step: 1,
        action: 'create_incident',
        type: PlaybookActionType.CASE_MANAGEMENT,
        description: 'Create a mock reconnaissance case for the scanning source and target set.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['incidentRecord'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 2,
        action: 'enrich_source_ip',
        type: PlaybookActionType.ENRICHMENT,
        description: 'Collect basic context for the scanning source, including known ownership or reputation notes.',
        requiredFields: ['sourceIp'],
        produces: ['sourceIpContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 3,
        action: 'check_target_asset',
        type: PlaybookActionType.ASSET_CONTEXT,
        description: 'Review whether the target asset is internet-facing, sensitive, or repeatedly probed.',
        requiredFields: ['targetIp'],
        produces: ['targetAssetContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 4,
        action: 'review_port_scan_evidence',
        type: PlaybookActionType.INVESTIGATION,
        description: 'Review the scan pattern, targeted ports, and repetition across hosts to estimate intent.',
        requiredFields: ['sourceIp', 'targetIp', 'protocol'],
        produces: ['reconnaissanceAssessment'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 5,
        action: 'prepare_firewall_block_request',
        type: PlaybookActionType.CONTAINMENT,
        description: 'Prepare a mock firewall block request if the source is assessed as hostile and persistent.',
        requiredFields: ['sourceIp'],
        produces: ['containmentRecommendation'],
        approvalRequired: true,
        risk: PlaybookStepRisk.SENSITIVE,
        mockOnly: true,
      }),
      buildAction({
        step: 6,
        action: 'mock_notify_analyst',
        type: PlaybookActionType.NOTIFICATION,
        description: 'Prepare a mock analyst notification with reconnaissance findings and recommended next steps.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['analystNotificationDraft'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 7,
        action: 'generate_response_summary',
        type: PlaybookActionType.REPORTING,
        description: 'Generate a concise reconnaissance summary for downstream recommendation and incident phases.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['responseSummary'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: false,
      }),
    ],
    approvalRequired: true,
    approvalPolicy: ApprovalPolicy.REQUIRED_FOR_SENSITIVE_ACTIONS,
    automationLevel: AutomationLevel.SEMI_AUTOMATED,
    status: PlaybookStatus.ACTIVE,
    references: [NIST_REFERENCE, MOCK_OPERATIONS_REFERENCE, THESIS_REFERENCE],
    version: '1.0.0',
    tags: ['seed', 'reconnaissance', 'port_scan', 'network'],
  },
  {
    playbookId: 'PB-003',
    name: 'ICMP Flood / DoS Response',
    description: 'Denial-of-service triage template for ICMP flooding or related service exhaustion indicators.',
    incidentCategory: IncidentCategory.DENIAL_OF_SERVICE,
    supportedAlertTypes: [AlertType.ICMP_FLOOD, AlertType.DOS_ATTEMPT],
    requiredFields: ['sourceIp', 'targetIp'],
    optionalFields: ['protocol', 'hostname', 'assetId'],
    severityRange: [Severity.MEDIUM, Severity.HIGH, Severity.CRITICAL],
    assetContext: ['internet_facing', 'network_edge', 'serviceOwner'],
    conditions: [
      buildCondition({
        field: 'alertType',
        operator: 'in',
        value: [AlertType.ICMP_FLOOD, AlertType.DOS_ATTEMPT],
        weightHint: 100,
        description: 'Applies to flooding or denial-of-service style alert types.',
      }),
      buildCondition({
        field: 'targetIp',
        operator: 'exists',
        description: 'Requires a victim target to review impact.',
      }),
    ],
    actions: [
      buildAction({
        step: 1,
        action: 'create_incident',
        type: PlaybookActionType.CASE_MANAGEMENT,
        description: 'Create a mock incident record for service degradation triage.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['incidentRecord'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 2,
        action: 'enrich_source_ip',
        type: PlaybookActionType.ENRICHMENT,
        description: 'Collect available context for the source system or network range driving the flood.',
        requiredFields: ['sourceIp'],
        produces: ['sourceIpContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 3,
        action: 'check_target_asset',
        type: PlaybookActionType.ASSET_CONTEXT,
        description: 'Review business criticality and exposure of the targeted service or gateway.',
        requiredFields: ['targetIp'],
        produces: ['targetAssetContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 4,
        action: 'investigate_service_impact',
        type: PlaybookActionType.INVESTIGATION,
        description: 'Determine whether the alert corresponds to observable service impact or elevated packet volume.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['impactAssessment'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 5,
        action: 'recommend_rate_limit',
        type: PlaybookActionType.CONTAINMENT,
        description: 'Prepare a mock recommendation for upstream rate limiting or traffic filtering.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['containmentRecommendation'],
        approvalRequired: true,
        risk: PlaybookStepRisk.SENSITIVE,
        mockOnly: true,
      }),
      buildAction({
        step: 6,
        action: 'mock_notify_service_owner',
        type: PlaybookActionType.NOTIFICATION,
        description: 'Prepare a mock owner notification describing service impact and recommended coordination.',
        requiredFields: ['targetIp'],
        produces: ['ownerNotificationDraft'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 7,
        action: 'generate_response_summary',
        type: PlaybookActionType.REPORTING,
        description: 'Generate a short incident-response summary of DoS indicators, impact, and mock containment advice.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['responseSummary'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: false,
      }),
    ],
    approvalRequired: true,
    approvalPolicy: ApprovalPolicy.REQUIRED_FOR_SENSITIVE_ACTIONS,
    automationLevel: AutomationLevel.SEMI_AUTOMATED,
    status: PlaybookStatus.ACTIVE,
    references: [NIST_REFERENCE, MOCK_OPERATIONS_REFERENCE, THESIS_REFERENCE],
    version: '1.0.0',
    tags: ['seed', 'dos', 'icmp_flood', 'availability'],
  },
  {
    playbookId: 'PB-004',
    name: 'Web SQL Injection Response',
    description: 'Web attack triage template for suspected SQL injection against an application endpoint.',
    incidentCategory: IncidentCategory.WEB_ATTACK,
    supportedAlertTypes: [AlertType.WEB_SQL_INJECTION],
    requiredFields: ['httpUri', 'sourceIp', 'targetIp'],
    optionalFields: ['hostname', 'assetId', 'username'],
    severityRange: [Severity.MEDIUM, Severity.HIGH, Severity.CRITICAL],
    assetContext: ['web_application', 'databaseDependency', 'serviceOwner'],
    conditions: [
      buildCondition({
        field: 'alertType',
        operator: 'equals',
        value: AlertType.WEB_SQL_INJECTION,
        weightHint: 100,
        description: 'Directly matches SQL injection alert types.',
      }),
      buildCondition({
        field: 'httpUri',
        operator: 'exists',
        description: 'Requires URI context for request review.',
      }),
    ],
    actions: [
      buildAction({
        step: 1,
        action: 'create_incident',
        type: PlaybookActionType.CASE_MANAGEMENT,
        description: 'Create a mock web attack incident record for the affected endpoint.',
        requiredFields: ['httpUri', 'targetIp'],
        produces: ['incidentRecord'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 2,
        action: 'enrich_source_ip',
        type: PlaybookActionType.ENRICHMENT,
        description: 'Collect available context for the attacking source and related requests.',
        requiredFields: ['sourceIp'],
        produces: ['sourceIpContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 3,
        action: 'check_target_asset',
        type: PlaybookActionType.ASSET_CONTEXT,
        description: 'Review application criticality, ownership, and whether the target is internet-facing.',
        requiredFields: ['targetIp'],
        produces: ['targetAssetContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 4,
        action: 'review_http_evidence',
        type: PlaybookActionType.INVESTIGATION,
        description: 'Inspect the URI, suspicious parameters, and any evidence of database-oriented payloads.',
        requiredFields: ['httpUri', 'sourceIp'],
        produces: ['webAttackAssessment'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 5,
        action: 'prepare_waf_rule_request',
        type: PlaybookActionType.CONTAINMENT,
        description: 'Prepare a mock request for WAF or virtual patching rules if the attack is confirmed.',
        requiredFields: ['httpUri'],
        produces: ['containmentRecommendation'],
        approvalRequired: true,
        risk: PlaybookStepRisk.SENSITIVE,
        mockOnly: true,
      }),
      buildAction({
        step: 6,
        action: 'mock_notify_analyst',
        type: PlaybookActionType.NOTIFICATION,
        description: 'Prepare a mock analyst notification with attack evidence and mock containment advice.',
        requiredFields: ['httpUri', 'sourceIp', 'targetIp'],
        produces: ['analystNotificationDraft'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 7,
        action: 'generate_response_summary',
        type: PlaybookActionType.REPORTING,
        description: 'Generate a concise SQL injection response summary for later recommendation explanation.',
        requiredFields: ['httpUri', 'sourceIp', 'targetIp'],
        produces: ['responseSummary'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: false,
      }),
    ],
    approvalRequired: true,
    approvalPolicy: ApprovalPolicy.REQUIRED_FOR_SENSITIVE_ACTIONS,
    automationLevel: AutomationLevel.SEMI_AUTOMATED,
    status: PlaybookStatus.ACTIVE,
    references: [NIST_REFERENCE, MOCK_OPERATIONS_REFERENCE, THESIS_REFERENCE],
    version: '1.0.0',
    tags: ['seed', 'web_attack', 'sql_injection', 'application'],
  },
  {
    playbookId: 'PB-005',
    name: 'Web XSS Response',
    description: 'Web attack triage template for suspected reflected or stored cross-site scripting activity.',
    incidentCategory: IncidentCategory.WEB_ATTACK,
    supportedAlertTypes: [AlertType.WEB_XSS],
    requiredFields: ['httpUri', 'sourceIp', 'targetIp'],
    optionalFields: ['hostname', 'assetId', 'username'],
    severityRange: [Severity.LOW, Severity.MEDIUM, Severity.HIGH],
    assetContext: ['web_application', 'userFacingPortal', 'serviceOwner'],
    conditions: [
      buildCondition({
        field: 'alertType',
        operator: 'equals',
        value: AlertType.WEB_XSS,
        weightHint: 100,
        description: 'Directly matches XSS alert types.',
      }),
      buildCondition({
        field: 'httpUri',
        operator: 'exists',
        description: 'Requires request context for script review.',
      }),
    ],
    actions: [
      buildAction({
        step: 1,
        action: 'create_incident',
        type: PlaybookActionType.CASE_MANAGEMENT,
        description: 'Create a mock XSS investigation record for the affected page or endpoint.',
        requiredFields: ['httpUri', 'targetIp'],
        produces: ['incidentRecord'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 2,
        action: 'enrich_url',
        type: PlaybookActionType.ENRICHMENT,
        description: 'Collect URL context and any related request indicators around the suspicious script payload.',
        requiredFields: ['httpUri'],
        produces: ['urlContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 3,
        action: 'check_target_asset',
        type: PlaybookActionType.ASSET_CONTEXT,
        description: 'Review whether the affected web asset handles sensitive user sessions or public content.',
        requiredFields: ['targetIp'],
        produces: ['targetAssetContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 4,
        action: 'review_http_evidence',
        type: PlaybookActionType.INVESTIGATION,
        description: 'Review request evidence for script injection patterns and potential user impact.',
        requiredFields: ['httpUri', 'sourceIp'],
        produces: ['webAttackAssessment'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 5,
        action: 'prepare_input_filter_update_request',
        type: PlaybookActionType.CONTAINMENT,
        description: 'Prepare a mock request for input filtering or content sanitization changes.',
        requiredFields: ['httpUri'],
        produces: ['containmentRecommendation'],
        approvalRequired: true,
        risk: PlaybookStepRisk.SENSITIVE,
        mockOnly: true,
      }),
      buildAction({
        step: 6,
        action: 'mock_notify_analyst',
        type: PlaybookActionType.NOTIFICATION,
        description: 'Prepare a mock analyst notification with suspected XSS evidence and user-impact notes.',
        requiredFields: ['httpUri', 'targetIp'],
        produces: ['analystNotificationDraft'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 7,
        action: 'generate_response_summary',
        type: PlaybookActionType.REPORTING,
        description: 'Generate a concise XSS response summary for future recommendation explanation and case review.',
        requiredFields: ['httpUri', 'targetIp'],
        produces: ['responseSummary'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: false,
      }),
    ],
    approvalRequired: true,
    approvalPolicy: ApprovalPolicy.REQUIRED_FOR_SENSITIVE_ACTIONS,
    automationLevel: AutomationLevel.SEMI_AUTOMATED,
    status: PlaybookStatus.ACTIVE,
    references: [NIST_REFERENCE, MOCK_OPERATIONS_REFERENCE, THESIS_REFERENCE],
    version: '1.0.0',
    tags: ['seed', 'web_attack', 'xss', 'application'],
  },
  {
    playbookId: 'PB-006',
    name: 'Suspicious DNS Investigation',
    description: 'DNS triage template for suspicious query patterns, possible beaconing, or domain abuse indicators.',
    incidentCategory: IncidentCategory.SUSPICIOUS_DNS,
    supportedAlertTypes: [AlertType.SUSPICIOUS_DNS_QUERY],
    requiredFields: ['dnsQuery', 'sourceIp'],
    optionalFields: ['targetIp', 'hostname', 'assetId'],
    severityRange: [Severity.LOW, Severity.MEDIUM, Severity.HIGH],
    assetContext: ['endpoint', 'dnsResolver', 'userDevice'],
    conditions: [
      buildCondition({
        field: 'alertType',
        operator: 'equals',
        value: AlertType.SUSPICIOUS_DNS_QUERY,
        weightHint: 100,
        description: 'Directly matches suspicious DNS query alerts.',
      }),
      buildCondition({
        field: 'dnsQuery',
        operator: 'exists',
        description: 'Requires domain context for investigation.',
      }),
    ],
    actions: [
      buildAction({
        step: 1,
        action: 'create_incident',
        type: PlaybookActionType.CASE_MANAGEMENT,
        description: 'Create a mock DNS investigation record for the querying host and domain.',
        requiredFields: ['dnsQuery', 'sourceIp'],
        produces: ['incidentRecord'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 2,
        action: 'enrich_domain',
        type: PlaybookActionType.ENRICHMENT,
        description: 'Collect domain context, recent observations, and any known suspicion indicators.',
        requiredFields: ['dnsQuery'],
        produces: ['domainContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 3,
        action: 'check_asset_context',
        type: PlaybookActionType.ASSET_CONTEXT,
        description: 'Review whether the querying asset is sensitive, shared, or repeatedly contacting uncommon domains.',
        requiredFields: ['sourceIp'],
        produces: ['assetContextReview'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 4,
        action: 'review_dns_evidence',
        type: PlaybookActionType.INVESTIGATION,
        description: 'Review the domain string, query pattern, and related notes for beaconing or tunneling suspicion.',
        requiredFields: ['dnsQuery', 'sourceIp'],
        produces: ['dnsInvestigationNotes'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 5,
        action: 'prepare_domain_block_request',
        type: PlaybookActionType.CONTAINMENT,
        description: 'Prepare a mock domain block request if the domain is assessed as malicious or policy-violating.',
        requiredFields: ['dnsQuery'],
        produces: ['containmentRecommendation'],
        approvalRequired: true,
        risk: PlaybookStepRisk.SENSITIVE,
        mockOnly: true,
      }),
      buildAction({
        step: 6,
        action: 'mock_notify_analyst',
        type: PlaybookActionType.NOTIFICATION,
        description: 'Prepare a mock analyst notification with domain findings and recommended next steps.',
        requiredFields: ['dnsQuery', 'sourceIp'],
        produces: ['analystNotificationDraft'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 7,
        action: 'generate_response_summary',
        type: PlaybookActionType.REPORTING,
        description: 'Generate a concise DNS investigation summary for later recommendation and incident phases.',
        requiredFields: ['dnsQuery', 'sourceIp'],
        produces: ['responseSummary'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: false,
      }),
    ],
    approvalRequired: true,
    approvalPolicy: ApprovalPolicy.REQUIRED_FOR_SENSITIVE_ACTIONS,
    automationLevel: AutomationLevel.SEMI_AUTOMATED,
    status: PlaybookStatus.ACTIVE,
    references: [NIST_REFERENCE, MOCK_OPERATIONS_REFERENCE, THESIS_REFERENCE],
    version: '1.0.0',
    tags: ['seed', 'dns', 'suspicious_dns', 'investigation'],
  },
  {
    playbookId: 'PB-007',
    name: 'Malware / C2 Traffic Investigation',
    description: 'Malware-oriented triage template for command-and-control traffic or confirmed malicious network communication.',
    incidentCategory: IncidentCategory.MALWARE,
    supportedAlertTypes: [AlertType.MALWARE_TRAFFIC, AlertType.BOTNET_C2],
    requiredFields: ['sourceIp', 'targetIp'],
    optionalFields: ['hostname', 'assetId', 'dnsQuery', 'httpUri'],
    severityRange: [Severity.MEDIUM, Severity.HIGH, Severity.CRITICAL],
    assetContext: ['endpoint', 'server', 'egressControl'],
    conditions: [
      buildCondition({
        field: 'alertType',
        operator: 'in',
        value: [AlertType.MALWARE_TRAFFIC, AlertType.BOTNET_C2],
        weightHint: 100,
        description: 'Applies to suspicious malware traffic and botnet C2 style alerts.',
      }),
      buildCondition({
        field: 'sourceIp',
        operator: 'exists',
        description: 'Requires a local source host for investigation.',
      }),
    ],
    actions: [
      buildAction({
        step: 1,
        action: 'create_incident',
        type: PlaybookActionType.CASE_MANAGEMENT,
        description: 'Create a mock malware investigation case for the communicating host.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['incidentRecord'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 2,
        action: 'enrich_source_ip',
        type: PlaybookActionType.ENRICHMENT,
        description: 'Collect host and network context for the suspected infected source.',
        requiredFields: ['sourceIp'],
        produces: ['sourceHostContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 3,
        action: 'check_asset_context',
        type: PlaybookActionType.ASSET_CONTEXT,
        description: 'Review host criticality, business function, and whether the host has privileged access.',
        requiredFields: ['sourceIp'],
        produces: ['assetContextReview'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 4,
        action: 'review_network_evidence',
        type: PlaybookActionType.INVESTIGATION,
        description: 'Review C2 indicators, repeated outbound communication, and related DNS or HTTP artifacts.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['malwareInvestigationNotes'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 5,
        action: 'prepare_host_isolation_request',
        type: PlaybookActionType.CONTAINMENT,
        description: 'Prepare a mock host isolation or egress restriction request for analyst approval.',
        requiredFields: ['sourceIp'],
        produces: ['containmentRecommendation'],
        approvalRequired: true,
        risk: PlaybookStepRisk.SENSITIVE,
        mockOnly: true,
      }),
      buildAction({
        step: 6,
        action: 'mock_notify_analyst',
        type: PlaybookActionType.NOTIFICATION,
        description: 'Prepare a mock analyst notification summarizing suspected malware communication and risk.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['analystNotificationDraft'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 7,
        action: 'generate_response_summary',
        type: PlaybookActionType.REPORTING,
        description: 'Generate a concise malware traffic summary for future recommendation and incident tracking.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['responseSummary'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: false,
      }),
    ],
    approvalRequired: true,
    approvalPolicy: ApprovalPolicy.REQUIRED_FOR_SENSITIVE_ACTIONS,
    automationLevel: AutomationLevel.SEMI_AUTOMATED,
    status: PlaybookStatus.ACTIVE,
    references: [NIST_REFERENCE, MOCK_OPERATIONS_REFERENCE, THESIS_REFERENCE],
    version: '1.0.0',
    tags: ['seed', 'malware', 'c2', 'network'],
  },
  {
    playbookId: 'PB-008',
    name: 'Brute Force Login Investigation',
    description: 'Identity-focused triage template for repeated authentication failures or probable credential attacks.',
    incidentCategory: IncidentCategory.BRUTE_FORCE,
    supportedAlertTypes: [AlertType.BRUTE_FORCE],
    requiredFields: ['sourceIp', 'username'],
    optionalFields: ['targetIp', 'hostname', 'assetId'],
    severityRange: [Severity.LOW, Severity.MEDIUM, Severity.HIGH],
    assetContext: ['identity', 'server', 'vpnGateway'],
    conditions: [
      buildCondition({
        field: 'alertType',
        operator: 'equals',
        value: AlertType.BRUTE_FORCE,
        weightHint: 100,
        description: 'Directly matches brute force authentication alerts.',
      }),
      buildCondition({
        field: 'username',
        operator: 'exists',
        description: 'Requires account context for investigation.',
      }),
    ],
    actions: [
      buildAction({
        step: 1,
        action: 'create_incident',
        type: PlaybookActionType.CASE_MANAGEMENT,
        description: 'Create a mock identity attack incident for the affected account and source.',
        requiredFields: ['sourceIp', 'username'],
        produces: ['incidentRecord'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 2,
        action: 'enrich_source_ip',
        type: PlaybookActionType.ENRICHMENT,
        description: 'Collect source context, including whether the login source is expected or unusual.',
        requiredFields: ['sourceIp'],
        produces: ['sourceIpContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 3,
        action: 'identify_affected_account',
        type: PlaybookActionType.ASSET_CONTEXT,
        description: 'Review account criticality, role, and any related asset ownership notes.',
        requiredFields: ['username'],
        produces: ['accountContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 4,
        action: 'review_authentication_evidence',
        type: PlaybookActionType.INVESTIGATION,
        description: 'Review failure volume, account targeting, and timing to distinguish noise from attack behavior.',
        requiredFields: ['sourceIp', 'username'],
        produces: ['authenticationAssessment'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 5,
        action: 'request_password_reset',
        type: PlaybookActionType.CONTAINMENT,
        description: 'Prepare a mock request for credential reset or access hardening if compromise risk is elevated.',
        requiredFields: ['username'],
        produces: ['containmentRecommendation'],
        approvalRequired: true,
        risk: PlaybookStepRisk.SENSITIVE,
        mockOnly: true,
      }),
      buildAction({
        step: 6,
        action: 'mock_notify_analyst',
        type: PlaybookActionType.NOTIFICATION,
        description: 'Prepare a mock analyst notification with account risk and recommended protective steps.',
        requiredFields: ['username', 'sourceIp'],
        produces: ['analystNotificationDraft'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 7,
        action: 'generate_response_summary',
        type: PlaybookActionType.REPORTING,
        description: 'Generate a concise brute force investigation summary for later recommendation and incident phases.',
        requiredFields: ['username', 'sourceIp'],
        produces: ['responseSummary'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: false,
      }),
    ],
    approvalRequired: true,
    approvalPolicy: ApprovalPolicy.REQUIRED_FOR_SENSITIVE_ACTIONS,
    automationLevel: AutomationLevel.SEMI_AUTOMATED,
    status: PlaybookStatus.ACTIVE,
    references: [NIST_REFERENCE, MOCK_OPERATIONS_REFERENCE, THESIS_REFERENCE],
    version: '1.0.0',
    tags: ['seed', 'brute_force', 'identity', 'authentication'],
  },
  {
    playbookId: 'PB-009',
    name: 'Phishing Alert Triage',
    description: 'Email-oriented triage template for suspicious phishing indicators or user-reported phishing alerts.',
    incidentCategory: IncidentCategory.PHISHING,
    supportedAlertTypes: [AlertType.PHISHING],
    requiredFields: ['title', 'severity'],
    optionalFields: ['username', 'httpUri', 'dnsQuery'],
    severityRange: [Severity.LOW, Severity.MEDIUM, Severity.HIGH],
    assetContext: ['user', 'mailbox', 'endpoint'],
    conditions: [
      buildCondition({
        field: 'alertType',
        operator: 'equals',
        value: AlertType.PHISHING,
        weightHint: 100,
        description: 'Directly matches phishing alert types.',
      }),
      buildCondition({
        field: 'username',
        operator: 'exists',
        description: 'Account context strengthens phishing triage.',
      }),
    ],
    actions: [
      buildAction({
        step: 1,
        action: 'create_incident',
        type: PlaybookActionType.CASE_MANAGEMENT,
        description: 'Create a mock phishing triage record for the affected user or message thread.',
        requiredFields: ['title', 'severity'],
        produces: ['incidentRecord'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 2,
        action: 'enrich_url',
        type: PlaybookActionType.ENRICHMENT,
        description: 'Collect context for any URL or indicator attached to the suspected phishing event.',
        requiredFields: ['title'],
        produces: ['urlContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 3,
        action: 'identify_affected_account',
        type: PlaybookActionType.ASSET_CONTEXT,
        description: 'Review affected user context, role sensitivity, and potential exposure scope.',
        requiredFields: ['title'],
        produces: ['accountContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 4,
        action: 'investigate_message_evidence',
        type: PlaybookActionType.INVESTIGATION,
        description: 'Review available indicators, delivery context, and whether the event suggests user interaction.',
        requiredFields: ['title'],
        produces: ['phishingAssessment'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 5,
        action: 'prepare_mailbox_containment_request',
        type: PlaybookActionType.CONTAINMENT,
        description: 'Prepare a mock request for mailbox review, message removal, or account protection steps.',
        requiredFields: ['title'],
        produces: ['containmentRecommendation'],
        approvalRequired: true,
        risk: PlaybookStepRisk.SENSITIVE,
        mockOnly: true,
      }),
      buildAction({
        step: 6,
        action: 'mock_notify_analyst',
        type: PlaybookActionType.NOTIFICATION,
        description: 'Prepare a mock analyst notification summarizing phishing indicators and user exposure risk.',
        requiredFields: ['title'],
        produces: ['analystNotificationDraft'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 7,
        action: 'generate_response_summary',
        type: PlaybookActionType.REPORTING,
        description: 'Generate a concise phishing triage summary for downstream explanation and case tracking.',
        requiredFields: ['title'],
        produces: ['responseSummary'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: false,
      }),
    ],
    approvalRequired: true,
    approvalPolicy: ApprovalPolicy.REQUIRED_FOR_SENSITIVE_ACTIONS,
    automationLevel: AutomationLevel.MANUAL,
    status: PlaybookStatus.ACTIVE,
    references: [NIST_REFERENCE, MOCK_OPERATIONS_REFERENCE, THESIS_REFERENCE],
    version: '1.0.0',
    tags: ['seed', 'phishing', 'email', 'user'],
  },
  {
    playbookId: 'PB-010',
    name: 'Data Exfiltration Investigation',
    description: 'Investigation template for alerts suggesting unusual outbound transfer or likely data exfiltration behavior.',
    incidentCategory: IncidentCategory.DATA_EXFILTRATION,
    supportedAlertTypes: [AlertType.DATA_EXFILTRATION],
    requiredFields: ['sourceIp', 'targetIp'],
    optionalFields: ['hostname', 'assetId', 'protocol', 'username'],
    severityRange: [Severity.HIGH, Severity.CRITICAL],
    assetContext: ['server', 'sensitiveDataStore', 'egressControl'],
    conditions: [
      buildCondition({
        field: 'alertType',
        operator: 'equals',
        value: AlertType.DATA_EXFILTRATION,
        weightHint: 100,
        description: 'Directly matches data exfiltration alert types.',
      }),
      buildCondition({
        field: 'sourceIp',
        operator: 'exists',
        description: 'Requires a source asset for data-scope review.',
      }),
      buildCondition({
        field: 'targetIp',
        operator: 'exists',
        description: 'Requires a destination endpoint or service for outbound analysis.',
      }),
    ],
    actions: [
      buildAction({
        step: 1,
        action: 'create_incident',
        type: PlaybookActionType.CASE_MANAGEMENT,
        description: 'Create a mock high-severity case for suspected outbound data transfer.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['incidentRecord'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 2,
        action: 'enrich_source_ip',
        type: PlaybookActionType.ENRICHMENT,
        description: 'Collect host and ownership context for the system suspected of transmitting data.',
        requiredFields: ['sourceIp'],
        produces: ['sourceHostContext'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: true,
      }),
      buildAction({
        step: 3,
        action: 'check_asset_context',
        type: PlaybookActionType.ASSET_CONTEXT,
        description: 'Review whether the source asset handles regulated or high-value data.',
        requiredFields: ['sourceIp'],
        produces: ['assetContextReview'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 4,
        action: 'investigate_egress_evidence',
        type: PlaybookActionType.INVESTIGATION,
        description: 'Review outbound indicators, transfer pattern, and any user or process context supporting exfiltration suspicion.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['egressInvestigationNotes'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 5,
        action: 'prepare_data_egress_block_request',
        type: PlaybookActionType.CONTAINMENT,
        description: 'Prepare a mock request for controlled egress restriction or transfer review escalation.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['containmentRecommendation'],
        approvalRequired: true,
        risk: PlaybookStepRisk.SENSITIVE,
        mockOnly: true,
      }),
      buildAction({
        step: 6,
        action: 'mock_notify_analyst',
        type: PlaybookActionType.NOTIFICATION,
        description: 'Prepare a mock analyst notification emphasizing potential data exposure and urgency.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['analystNotificationDraft'],
        approvalRequired: false,
        risk: PlaybookStepRisk.REVIEW_REQUIRED,
        mockOnly: true,
      }),
      buildAction({
        step: 7,
        action: 'generate_response_summary',
        type: PlaybookActionType.REPORTING,
        description: 'Generate a concise exfiltration investigation summary for later recommendation and reporting phases.',
        requiredFields: ['sourceIp', 'targetIp'],
        produces: ['responseSummary'],
        approvalRequired: false,
        risk: PlaybookStepRisk.SAFE,
        mockOnly: false,
      }),
    ],
    approvalRequired: true,
    approvalPolicy: ApprovalPolicy.REQUIRED_FOR_SENSITIVE_ACTIONS,
    automationLevel: AutomationLevel.SEMI_AUTOMATED,
    status: PlaybookStatus.ACTIVE,
    references: [NIST_REFERENCE, MOCK_OPERATIONS_REFERENCE, THESIS_REFERENCE],
    version: '1.0.0',
    tags: ['seed', 'data_exfiltration', 'egress', 'high_severity'],
  },
];
