import {
  AlertType,
  AutomationLevel,
  Severity,
  type Playbook as SharedPlaybook,
} from '@soc-soar/shared';

type SeedPlaybook = Omit<SharedPlaybook, 'createdAt' | 'updatedAt'>;

export const PLAYBOOK_SEED_DATA: SeedPlaybook[] = [
  {
    playbookId: 'PB-001',
    name: 'Generic Alert Triage',
    description: 'Baseline analyst triage flow for alerts that require structured review.',
    incidentCategory: 'generic_triage',
    supportedAlertTypes: [AlertType.GENERIC],
    requiredFields: ['title', 'severity'],
    severityRange: [Severity.LOW, Severity.MEDIUM, Severity.HIGH, Severity.CRITICAL],
    assetContext: ['generic', 'unknown'],
    actions: [
      {
        step: 1,
        action: 'collect-basic-context',
        type: 'enrichment',
        description: 'Collect core alert context for analyst review.',
        approvalRequired: false,
        mockOnly: true,
      },
    ],
    approvalRequired: false,
    automationLevel: AutomationLevel.MANUAL,
    references: ['Initial thesis dataset placeholder'],
  },
  {
    playbookId: 'PB-002',
    name: 'Port Scan Investigation',
    description: 'Investigate likely reconnaissance activity from a single source.',
    incidentCategory: 'network_reconnaissance',
    supportedAlertTypes: [AlertType.PORT_SCAN],
    requiredFields: ['sourceIp', 'targetIp', 'protocol'],
    severityRange: [Severity.LOW, Severity.MEDIUM, Severity.HIGH],
    assetContext: ['server', 'network-edge'],
    actions: [
      {
        step: 1,
        action: 'review-scan-pattern',
        type: 'analysis',
        description: 'Review ports and hosts touched by the source.',
        approvalRequired: false,
        mockOnly: true,
      },
    ],
    approvalRequired: false,
    automationLevel: AutomationLevel.SEMI_AUTOMATED,
    references: ['Reconnaissance response placeholder'],
  },
  {
    playbookId: 'PB-003',
    name: 'ICMP Flood / DoS Response',
    description: 'Handle suspected volumetric or ICMP-focused denial-of-service activity.',
    incidentCategory: 'denial_of_service',
    supportedAlertTypes: [AlertType.ICMP_FLOOD, AlertType.DOS_ATTEMPT],
    requiredFields: ['sourceIp', 'targetIp'],
    severityRange: [Severity.MEDIUM, Severity.HIGH, Severity.CRITICAL],
    assetContext: ['internet-facing', 'network-edge'],
    actions: [
      {
        step: 1,
        action: 'confirm-service-impact',
        type: 'validation',
        description: 'Validate whether the destination asset is degraded.',
        approvalRequired: true,
        mockOnly: true,
      },
    ],
    approvalRequired: true,
    automationLevel: AutomationLevel.SEMI_AUTOMATED,
    references: ['Mock-only DoS coordination placeholder'],
  },
  {
    playbookId: 'PB-004',
    name: 'Web Attack Response',
    description: 'Review common web exploitation attempts such as SQL injection or XSS.',
    incidentCategory: 'web_attack',
    supportedAlertTypes: [AlertType.WEB_SQL_INJECTION, AlertType.WEB_XSS],
    requiredFields: ['httpUri', 'sourceIp', 'targetIp'],
    severityRange: [Severity.MEDIUM, Severity.HIGH, Severity.CRITICAL],
    assetContext: ['web', 'application'],
    actions: [
      {
        step: 1,
        action: 'inspect-request-artifact',
        type: 'analysis',
        description: 'Inspect suspicious URI and payload indicators.',
        approvalRequired: false,
        mockOnly: true,
      },
    ],
    approvalRequired: true,
    automationLevel: AutomationLevel.SEMI_AUTOMATED,
    references: ['Web app incident placeholder'],
  },
  {
    playbookId: 'PB-005',
    name: 'Suspicious DNS Investigation',
    description: 'Triage unusual DNS activity for beaconing, tunneling, or malicious resolution.',
    incidentCategory: 'dns_investigation',
    supportedAlertTypes: [AlertType.SUSPICIOUS_DNS_QUERY],
    requiredFields: ['dnsQuery', 'sourceIp'],
    severityRange: [Severity.LOW, Severity.MEDIUM, Severity.HIGH],
    assetContext: ['endpoint', 'dns'],
    actions: [
      {
        step: 1,
        action: 'review-domain-reputation',
        type: 'enrichment',
        description: 'Check whether the queried domain is suspicious.',
        approvalRequired: false,
        mockOnly: true,
      },
    ],
    approvalRequired: false,
    automationLevel: AutomationLevel.SEMI_AUTOMATED,
    references: ['DNS alert response placeholder'],
  },
  {
    playbookId: 'PB-006',
    name: 'Malware / C2 Traffic Investigation',
    description:
      'Investigate alert patterns related to malware traffic or botnet command and control.',
    incidentCategory: 'malware_traffic',
    supportedAlertTypes: [AlertType.MALWARE_TRAFFIC, AlertType.BOTNET_C2, AlertType.MALWARE_HASH],
    requiredFields: ['sourceIp', 'targetIp'],
    severityRange: [Severity.MEDIUM, Severity.HIGH, Severity.CRITICAL],
    assetContext: ['endpoint', 'server'],
    actions: [
      {
        step: 1,
        action: 'collect-host-indicators',
        type: 'enrichment',
        description: 'Collect host and network indicators for analyst review.',
        approvalRequired: false,
        mockOnly: true,
      },
    ],
    approvalRequired: true,
    automationLevel: AutomationLevel.SEMI_AUTOMATED,
    references: ['Malware containment is mock-only in this phase'],
  },
  {
    playbookId: 'PB-007',
    name: 'Brute Force Login Investigation',
    description: 'Investigate repeated authentication failures or suspected password attacks.',
    incidentCategory: 'identity_attack',
    supportedAlertTypes: [AlertType.BRUTE_FORCE],
    requiredFields: ['sourceIp', 'targetIp'],
    severityRange: [Severity.LOW, Severity.MEDIUM, Severity.HIGH],
    assetContext: ['identity', 'endpoint', 'server'],
    actions: [
      {
        step: 1,
        action: 'review-authentication-pattern',
        type: 'analysis',
        description: 'Review failure volume and target account patterns.',
        approvalRequired: false,
        mockOnly: true,
      },
    ],
    approvalRequired: true,
    automationLevel: AutomationLevel.SEMI_AUTOMATED,
    references: ['Login attack response placeholder'],
  },
  {
    playbookId: 'PB-008',
    name: 'Phishing Alert Triage',
    description: 'Perform first-pass analyst triage for phishing-related alerts.',
    incidentCategory: 'phishing',
    supportedAlertTypes: [AlertType.PHISHING],
    requiredFields: ['title', 'severity'],
    severityRange: [Severity.LOW, Severity.MEDIUM, Severity.HIGH],
    assetContext: ['email', 'user'],
    actions: [
      {
        step: 1,
        action: 'validate-phishing-context',
        type: 'analysis',
        description: 'Validate the message or artifact context that triggered the alert.',
        approvalRequired: false,
        mockOnly: true,
      },
    ],
    approvalRequired: false,
    automationLevel: AutomationLevel.MANUAL,
    references: ['Phishing dataset placeholder'],
  },
];
